[package]
name = "pipo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-recursion = "0.3"
chrono = "0.4"
deadpool-sqlite = "0.1"
emojis = "0.1"
futures = "0.3"
irc = "0.15"
lazy_static = "1.4"
regex = "1.5"
reqwest = "0.11"
rusqlite = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serenity = { version = "0.10", default_features = false, features = ["client", "gateway", "native_tls_backend", "model"] }
tokio = { version = "1.10", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-tungstenite = { version = "0.15", features = ["native-tls"] }
